# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1slFhG6Mr11mLsycUxSP6W8-FwDML7ZET
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import os

# ============================================================
# CONFIGURACIÓN DE PÁGINA
# ============================================================

st.set_page_config(
    page_title="Netflix Churn Predictor",
    page_icon="🎬",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.title("🎬 Predictor de Cancelación de Clientes Netflix")
st.markdown("**Grupo 3** | Modelo de Clasificación - Predicción de Churn")

# ============================================================
# CARGAR MODELO PRE-ENTRENADO
# ============================================================

@st.cache_resource
def cargar_modelo():
    """Carga el modelo pre-entrenado una sola vez al iniciar la app"""
    try:
        modelo = joblib.load('modelo_netflix_churn.pkl')
        return modelo
    except FileNotFoundError:
        st.error("❌ Archivo 'modelo_netflix_churn.pkl' no encontrado. "
                 "Verifica que esté en el mismo directorio que app.py")
        st.stop()

modelo = cargar_modelo()

# ============================================================
# SIDEBAR: INFORMACIÓN DEL MODELO
# ============================================================

with st.sidebar:
    st.markdown("### 📊 Información del Modelo")
    st.markdown("""
    **Algoritmo**: Random Forest Optimizado

    **Métricas en Test**:
    - Recall: 0.956 (95.6% de churns detectados)
    - F1-Score: 0.924
    - ROC-AUC: 0.989
    - Precision: 0.895

    **Variables usadas**: 12 features
    - 5 numéricas
    - 1 ordinal
    - 6 categóricas
    """)

    st.divider()

    st.markdown("### 💡 ¿Qué es la probabilidad de churn?")
    st.markdown("""
    Es la **confianza del modelo** de que un cliente cancelará su suscripción.

    - **0.0 - 0.33**: Riesgo Bajo
    - **0.33 - 0.66**: Riesgo Medio
    - **0.66 - 1.00**: Riesgo Alto
    """)

# ============================================================
# SECCIÓN DE ENTRADA DE DATOS
# ============================================================

st.markdown("### 📝 Ingresa los datos del cliente")

col1, col2, col3 = st.columns(3)

with col1:
    edad = st.number_input(
        "Edad",
        min_value=18,
        max_value=100,
        value=30,
        step=1
    )

    genero = st.selectbox(
        "Género",
        options=["Male", "Female"]
    )

    tipo_subscripcion = st.selectbox(
        "Tipo de Suscripción",
        options=["Basic", "Standard", "Premium"]
    )

with col2:
    horas_de_vista = st.number_input(
        "Horas de Vista (últimos 30 días)",
        min_value=0.0,
        max_value=200.0,
        value=15.5,
        step=0.5
    )

    ultimos_dias_login = st.number_input(
        "Días desde el último login",
        min_value=0,
        max_value=120,
        value=7,
        step=1
    )

    numero_perfiles = st.number_input(
        "Número de perfiles en la cuenta",
        min_value=1,
        max_value=10,
        value=2,
        step=1
    )

with col3:
    promedio_visualizacion_dia = st.number_input(
        "Promedio de visualización diaria (horas)",
        min_value=0.0,
        max_value=10.0,
        value=2.1,
        step=0.1
    )

    region = st.selectbox(
        "Región",
        options=["US", "EU", "LATAM", "ASIA"]
    )

    dispositivo = st.selectbox(
        "Dispositivo Principal",
        options=["Mobile", "Tablet", "Laptop", "Smart TV"]
    )

col_extra1, col_extra2 = st.columns(2)

with col_extra1:
    metodo_pago = st.selectbox(
        "Método de Pago",
        options=["Credit Card", "Debit Card", "Digital Wallet", "Bank Transfer"]
    )

with col_extra2:
    genero_favorito = st.selectbox(
        "Género Favorito",
        options=["Action", "Comedy", "Documentary", "Drama", "Horror", "Romance", "Sci-Fi", "Thriller"]
    )

# ============================================================
# PREDICCIÓN
# ============================================================

st.divider()

if st.button("🔮 Predecir Riesgo de Churn", use_container_width=True, type="primary"):

    # Construir DataFrame con los datos ingresados
    datos_cliente = pd.DataFrame({
        'edad': [edad],
        'genero': [genero],
        'tipo_subscripcion': [tipo_subscripcion],
        'horas_de_vista': [horas_de_vista],
        'ultimos_dias_login': [ultimos_dias_login],
        'numero_perfiles': [numero_perfiles],
        'promedio_visualizacion_dia': [promedio_visualizacion_dia],
        'region': [region],
        'dispositivo': [dispositivo],
        'metodo_pago': [metodo_pago],
        'genero_favorito': [genero_favorito]
    })

    # Hacer predicción
    prediccion = modelo.predict(datos_cliente)[0]
    probabilidad_churn = modelo.predict_proba(datos_cliente)[0][1]

    # Clasificar riesgo
    if probabilidad_churn < 0.33:
        nivel_riesgo = "🟢 Riesgo Bajo"
        color_riesgo = "green"
    elif probabilidad_churn < 0.66:
        nivel_riesgo = "🟡 Riesgo Medio"
        color_riesgo = "orange"
    else:
        nivel_riesgo = "🔴 Riesgo Alto"
        color_riesgo = "red"

    # Mostrar resultados
    st.markdown("---")
    st.markdown("### 📈 Resultados de la Predicción")

    res_col1, res_col2, res_col3 = st.columns(3)

    with res_col1:
        st.metric(
            "Probabilidad de Churn",
            f"{probabilidad_churn:.1%}",
            delta=f"{probabilidad_churn:.4f}"
        )

    with res_col2:
        st.markdown(f"<h3 style='text-align: center; color: {color_riesgo};'>{nivel_riesgo}</h3>",
                   unsafe_allow_html=True)

    with res_col3:
        prediccion_texto = "Cancelará" if prediccion == 1 else "Permanecerá"
        st.metric("Predicción", prediccion_texto)

    st.markdown("---")

    # Explicación detallada
    st.markdown("### 💬 Interpretación")

    if probabilidad_churn < 0.33:
        explicacion = f"""
        Este cliente tiene una probabilidad de **{probabilidad_churn:.1%}** de cancelar su suscripción.
        Según nuestro modelo, es muy probable que continúe siendo un cliente activo.
        **No se requieren acciones inmediatas de retención.**
        """
    elif probabilidad_churn < 0.66:
        explicacion = f"""
        Este cliente tiene una probabilidad de **{probabilidad_churn:.1%}** de cancelar.
        Está en una zona intermedia. **Se recomienda monitoreo** y posiblemente
        ofrecer promociones o contenido personalizado para mejorar su experiencia.
        """
    else:
        explicacion = f"""
        Este cliente tiene una probabilidad de **{probabilidad_churn:.1%}** de cancelar.
        **Se requiere atención inmediata.** Considera:
        - Ofertas especiales de retención
        - Llamadas de seguimiento personalizado
        - Análisis de por qué podría estar insatisfecho
        """

    st.info(explicacion)

    # Tabla resumen
    st.markdown("### 📋 Resumen del Cliente")
    resumen_df = pd.DataFrame({
        'Característica': ['Edad', 'Género', 'Tipo de Suscripción', 'Horas vistas',
                          'Días sin login', 'Número de perfiles', 'Visualización diaria',
                          'Región', 'Dispositivo', 'Método pago', 'Género favorito'],
        'Valor': [edad, genero, tipo_subscripcion, horas_de_vista,
                 ultimos_dias_login, numero_perfiles, promedio_visualizacion_dia,
                 region, dispositivo, metodo_pago, genero_favorito]
    })
    st.dataframe(resumen_df, use_container_width=True, hide_index=True)

# ============================================================
# FOOTER
# ============================================================

st.divider()
st.markdown("""
<div style='text-align: center; color: gray; font-size: 0.9em;'>
    Desarrollado por Grupo 3 | Machine Learning & Data Science<br>
    Modelo entrenado con datos históricos de Netflix | Última actualización: 2026
</div>
""", unsafe_allow_html=True)